FROM --platform=$BUILDPLATFORM alpine:latest

RUN apk add --no-cache tftp-hpa

RUN mkdir -p /var/tftpboot && \
    chmod 755 /var/tftpboot

EXPOSE 69/udp

CMD ["/usr/sbin/in.tftpd", "-L", "-s", "/var/tftpboot", "-a", "0.0.0.0:69", "--verbose", "--create"]